### ISSUE TITLE
ROOT_CAがstatic.tts.questに対応していない問題

### ISSUE THREAD

**Issue by ts-klassen** [hollyhockberry/VoiceVoxClient#1]
ROOT_CAの証明書は、[Internet Security Research Groupの証明書](http://certificate.fyicenter.com/11467_ISRG_Root_X1_Certificate-79B459E67BB6E5E40173800888C81A58F6E99B6E.html)で、api.tts.quest, audio1.tts.quest, audio2.tts.questを保証しています。
https://github.com/hollyhockberry/VoiceVoxClient/blob/57bc9f5ef2b9f32d75aa96f2035dda0a5cf12689/src/VoiceVoxClient.cpp#L9

一方、static.tts.questのサーバー証明書はGoogle Trust Services LLCで発行されています。

したがって、Google Trust Services LLCの[GTS CA 1P5 Certificate](http://www.certificate.fyicenter.com/14777_GTS_CA_1P5_Certificate-D5FC9E0DDF1ECADD0897976E2BC55FC52BF5ECB8.html)を使うことで認証できるかもしれません。

**Comment by hollyhockberry** [comment]
ありがとうございます。
証明書はコンストラクタでもらう実装にしました。
（未設定の場合はInsecureで接続します）
